version: '3'

volumes:
  mongo_data:

services:
  application:
    container_name: dietcounter
    restart: always
    build: .
    ports:
      - '80:5000'
    links:
      - mongo
    environment:
      - ENVIROMENT=docker
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
